#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running types check"
npx tsc 
echo "Running tests"
npm run test
npm run test:badges
echo "Running lint check"
npm run lint
echo "Running code formatting"
npm run prettier